server:
  port: 8084
# 服务名称feign-server
spring:
  application:
    name: feign-server
# 连接服务注册中心eureka端口号8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
    registry-fetch-interval-seconds: 5  # 客户端从Eureka服务器获取注册信息的间隔时间
    lease-renewal-interval-in-seconds: 10  # 客户端发送心跳的间隔时间
    lease-expiration-duration-in-seconds: 30  # 实例过期的时间
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10  # 确保实例按时发送心跳
    lease-expiration-duration-in-seconds: 30
feign:
  client:
    config:
      default:
        loggerLevel: full