server:
  port: 8084
# ?????feign-server
spring:
  application:
    name: feign-server
# ????????eureka????????8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
feign:
  client:
    config:
      default:
        loggerLevel: full