server:
  port: 8081
spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-center
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service_route
          uri: lb://user-server
          predicates:
            - Path=/login
          filters:
            - name: CircuitBreaker
              args:
                name: clientCircuitBreaker
                fallbackUri: forward:/fallback
    circuitbreaker:
      # ??Resilience4j????
      resilience4j:
        instances:
          clientCircuitBreaker:
            registerHealthIndicator: true
            slidingWindowSize: 10
            minimumNumberOfCalls: 5
            failureRateThreshold: 50
            waitDurationInOpenState: 10000
            permittedNumberOfCallsInHalfOpenState: 3
            maxWaitDurationInHalfOpenState: 5000
            slidingWindowType: COUNT_BASED
            decorators:
              - name: TimeLimiter
                args:
                  timeoutDuration: 3000
eureka:
  client:
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8080/eureka/
  instance:
    instance-id: gateway
    prefer-ip-address: true
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
