server:
  port: 8081
spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-center
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service_route
          uri: lb://user-server
          predicates:
            - Path=/user-server/**
          filters:
            - name: CircuitBreaker
              args:
                name: clientCircuitBreaker
                fallbackUri: forward:/fallback
            - name: RewritePath
              args:
                regexp: /user-server/(?<remaining>.*)   # 将 /user-server/ 后的所有路径捕获到 remaining 变量中
                replacement: /${remaining}       # 将捕获的路径作为新的路径替换
        - id: common_route
          uri: lb://biz-common
          predicates:
            - Path=/biz-common/**
          filters:
            - name: CircuitBreaker
              args:
                name: clientCircuitBreaker
                fallbackUri: forward:/fallback
            - name: RewritePath
              args:
                regexp: /biz-common/(?<remaining>.*)   # 将 /user/ 后的所有路径捕获到 remaining 变量中
                replacement: /${remaining}       # 将捕获的路径作为新的路径替换
    circuitbreaker:
      # 配置Resilience4j熔断器
      resilience4j:
        instances:
          clientCircuitBreaker:
            registerHealthIndicator: true
            slidingWindowSize: 10
            minimumNumberOfCalls: 5
            failureRateThreshold: 50
            waitDurationInOpenState: 20000
            permittedNumberOfCallsInHalfOpenState: 3
            maxWaitDurationInHalfOpenState: 10000
            slidingWindowType: COUNT_BASED
            decorators:
              - name: TimeLimiter
                args:
                  timeoutDuration: 3000
eureka:
  client:
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8080/eureka/
    registry-fetch-interval-seconds: 5  # 客户端从Eureka服务器获取注册信息的间隔时间
    lease-renewal-interval-in-seconds: 10  # 客户端发送心跳的间隔时间
    lease-expiration-duration-in-seconds: 30  # 实例过期的时间

  instance:
    instance-id: gateway
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10  # 确保实例按时发送心跳
    lease-expiration-duration-in-seconds: 30
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
